content='type': 'text', 'text': "Today in Chennai, the weather is expected to be "
"**hot and humid** with a mix of sun and clouds. Here arethe details:\n\n*  "
" **Temperature:** High of around **37°C (99°F)** and a low of **28°C (82°F)**.\n*  "
" **RealFeel:** Due to high humidity, it will feel closer to **42°C–45°C**"
" during the afternoon.\n*   **Condition:** Mostly sunny or partly cloudy. "
"There is a **slight chance (around 20-30%) of isolated thundershowers** or light "
"rain in some parts of the city, likely towards the evening or night.\n*   "
"**Humidity:** High, hovering around **65% to 70%**.\n*   **Wind:** "
"Light breezes coming from the South/Southwest at about 15–20 km/h.\n\n"
"**Advice:** If youare heading out, stay hydrated and carry an umbrella just in case of a sudden"
" evening shower or to shield yourself from the sun.\n\n*(Note:Weather can change quickly; "
"for real-time updates, it's best to check a live source like Google Weather or AccuWeather."
")*"